version: "3.8"

services:
  db:
      image: mysql
      restart: always
      container_name: mysql-container
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_USER: user
        MYSQL_PASSWORD: 1234
        MYSQL_DATABASE: database
      ports:
        - "3306:3306"
      volumes:
        - mysql:/var/lib/mysql

volumes:
  mysql: